### ISSUE TITLE
(RFE) --terminate argparse for mass-schedule shortening

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#344] opened 2020-11-10 17:11 UTC
This is an argparse RFE to provide a command-set used to mass reduce the active schedule across a cloud.

_This would basically replace using a for loop for `--mod-schedule` to shorten the schedules across a cloud to terminate immediately._

* We should look into potentially having interactive confirmation unless `--force` is passed.

Example:

```
# quads-cli --terminate --cloud cloud02 --force
Cloud cloud02 is terminating on 2020-11-10 17:09
```

Extra points will be granted for clever Arnold quotes logger might reference in the codebase.

**Comment by grafuls** [comment] 2020-11-12 10:25
Closed as duplicate of:
https://github.com/redhat-performance/quads/issues/342

**Comment by sadsfae** [comment] 2020-11-13 13:21
This is not a duplicate, `--shrink` and `--terminate` do different things.

(--shrink)
* Cloud-level, inverse of `--extend--cloud`

(--terminate)
* Align all `--schedule-end` to date.time = now with some checks.

**Closed** 2020-11-13 13:22 UTC
Labels: enhancement, quads-cli, scheduling
