### ISSUE TITLE
Use ramdisk/livecd idea to wipe machines

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/quads#106] opened 2017-06-20 00:41 UTC
This RFE would need to be implemented first [ [issue48](https://github.com/redhat-performance/quads/issues/48) ]. 

We have seen where QUADs has moved machines into an existing cloud, and there was conflicting IPs from thew newly added machines. To avoid this, we could have a ramdisk / livecd wipe the newly added machines. Any time a machine moves clouds, we should invoke this cleaning.

**Comment by sadsfae** [comment] 2017-06-30 16:32
Closing this as a duplicate of https://github.com/redhat-performance/quads/issues/48

Let's operate out of that issue, also added milestone 1.0 for importance.

**Closed by sadsfae** 2017-06-30 16:32 UTC
Labels: enhancement
