### ISSUE TITLE
Validate IPMI credentials as part of systems validation

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#145] opened 2017-09-18 18:32 UTC
We currently validate systems deployment and network connectivity but we have some cases where new sets of machines are added and their IPMI credentials are not properly set.  This can cause an assignment to go out but introspection or user interaction to fail with out-of-band operations.

We should validate against the return status of a simple IPMI command to ensure the credentials are set correctly.

**Comment by grafuls** [comment] 2019-10-09 09:08
https://review.gerrithub.io/c/redhat-performance/quads/+/470815

**Comment by grafuls** [comment] 2019-10-09 09:17
Closing as duplicate of https://github.com/redhat-performance/quads/issues/280

**Closed by grafuls** 2019-10-09 09:17 UTC
Labels: enhancement
